sudo: required
services:
  - docker

before_install:
  - docker build -t siddharthat88/docker-react -f Dockerfile.dev .
script:
  - docker run CI=true siddharthat88/docker-react npm run test -- --coverage
